#!/bin/sh

# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/ACT%20-%20Apricot%20PC%20Xi/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/APF%20-%20Imagination%20Machine/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/APF%20-%20MP-1000/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Acorn%20-%20Archimedes%20%28ADF%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Acorn%20-%20Archimedes%20%28JFD%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Acorn%20-%20Atom%20%28Tapes%29%20%28UEF%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Acorn%20-%20Risc%20PC%20%28Pauline%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Acorn%20RISC%20OS%20-%20Flash%20Media%20%28Misc%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Amstrad%20-%20CPC%20%28FluxDumps%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Amstrad%20-%20CPC%20%28Misc%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Analogue%20-%20Analogue%20Pocket/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20I%20%28Tapes%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20II%20%28A2R%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20II%20%28WOZ%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20II%20%28Waveform%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20II%20Plus%20%28Flux%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20II%20Plus%20%28WOZ%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20IIGS%20%28A2R%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20IIGS%20%28WOZ%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20IIe%20%28A2R%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20IIe%20%28Kryoflux%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20IIe%20%28WOZ%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20Macintosh%20%28A2R%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20Macintosh%20%28BETA%29%20%28Bitstreams%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20Macintosh%20%28BETA%29%20%28FluxDumps%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20Macintosh%20%28DC42%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20Macintosh%20%28KryoFlux%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20Macintosh%20%28Uncategorized%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple%20-%20Macintosh%20%28WOZ%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Apple-Bandai%20-%20Pippin%20%28Floppies%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Atari%20-%202600/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Atari%20-%205200/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Atari%20-%207800/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Atari%20-%208-bit%20Family/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Atari%20-%208-bit%20Family%20%28Kryoflux%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Atari%20-%20Jaguar%20%28J64%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Atari%20-%20Jaguar%20%28ROM%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Atari%20-%20Lynx/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Atari%20-%20ST/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Atari%20-%20ST%20%28Flux%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Bally%20-%20Astrocade/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Bally%20-%20Astrocade%20%28Tapes%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Bally%20-%20Astrocade%20%28Tapes%29%20%28WAV%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Bandai%20-%20Design%20Master%20Denshi%20Mangajuku/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Bandai%20-%20Gundam%20RX-78/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Bandai%20-%20WonderSwan/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Bandai%20-%20WonderSwan%20Color/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Benesse%20-%20Pocket%20Challenge%20V2/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Benesse%20-%20Pocket%20Challenge%20W/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Bit%20Corporation%20-%20Gamate/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Casio%20-%20Loopy/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Casio%20-%20PV-1000/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Coleco%20-%20ColecoVision/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Commodore%20-%20Amiga/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Commodore%20-%20Amiga%20%28Flux%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Commodore%20-%20Commodore%2064/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Commodore%20-%20Commodore%2064%20%28PP%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Commodore%20-%20Commodore%2064%20%28Tapes%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Commodore%20-%20Plus-4/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Commodore%20-%20VIC-20/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Emerson%20-%20Arcadia%202001/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Entex%20-%20Adventure%20Vision/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Epoch%20-%20Game%20Pocket%20Computer/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Epoch%20-%20Super%20Cassette%20Vision/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Fairchild%20-%20Channel%20F/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Fujitsu%20-%20FM%20Towns%20%28KryoFlux%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Fujitsu%20-%20FM-7%20%28Flux%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Fujitsu%20-%20FM-7%20%28Waveform%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Fujitsu%20-%20FMR50%20%28Flux%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Fukutake%20Publishing%20-%20StudyBox/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Funtech%20-%20Super%20Acan/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/GCE%20-%20Vectrex/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/GamePark%20-%20GP2X/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/GamePark%20-%20GP32/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Google%20-%20Android%20%28Amazon%20Appstore%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Google%20-%20Android%20%28Misc%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Google%20-%20Android%20%28Samsung%20Galaxy%20Apps%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Hartung%20-%20Game%20Master/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Hitachi%20-%20S1%20%28Waveform%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/IBM%20-%20PC%20and%20Compatibles%20%28Digital%29%20%28Getchu.com%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/IBM%20-%20PC%20and%20Compatibles%20%28Digital%29%20%28Misc%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/IBM%20-%20PC%20and%20Compatibles%20%28Digital%29%20%28Steam%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/IBM%20-%20PC%20and%20Compatibles%20%28Digital%29%20%28itch.io%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Interton%20-%20VC%204000/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Konami%20-%20Picno/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/LeapFrog%20-%20LeapPad/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/LeapFrog%20-%20Leapster%20Learning%20Game%20System/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Luxor%20-%20ABC%20800%20%28Flux%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Magnavox%20-%20Odyssey%202/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Mattel%20-%20Intellivision/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Microsoft%20-%20MSX/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Microsoft%20-%20MSX2/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Microsoft%20-%20Xbox%20%28Development%20Kit%20Hard%20Drives%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Microsoft%20-%20Xbox%20360%20%28Digital%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Milton-Bradley%20-%20Omni%20%28Waveform%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Mobile%20-%20J2ME/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Mobile%20-%20Palm%20OS/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Mobile%20-%20Palm%20OS%20%28Digital%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Mobile%20-%20Pocket%20PC/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Mobile%20-%20Pocket%20PC%20%28Digital%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Mobile%20-%20Symbian/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/NEC%20-%20PC%20Engine%20-%20TurboGrafx%2016/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/NEC%20-%20PC%20Engine%20SuperGrafx/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/NEC%20-%20PC-88%20%28Flux%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/NEC%20-%20PC-88%20%28KryoFlux%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/NEC%20-%20PC-98/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/NEC%20-%20PC-98%20%28Flux%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/NEC%20-%20PC-98%20%28Greaseweazle%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/NEC%20-%20PC-98%20%28HardDisk%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/NEC%20-%20PC-98%20%28Uncategorized%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nichibutsu%20-%20My%20Vision/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Family%20BASIC%20%28Tapes%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Family%20Computer%20Disk%20System%20%28FDS%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Family%20Computer%20Disk%20System%20%28FDSStickRAW%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Family%20Computer%20Disk%20System%20%28QD%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Family%20Computer%20Network%20System/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Game%20%26%20Watch/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Game%20Boy/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance%20%28Multiboot%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance%20%28Video%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance%20%28e-Reader%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Game%20Boy%20Color/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Kiosk%20Video%20Compact%20Flash%20%28CardImage%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Kiosk%20Video%20Compact%20Flash%20%28Extracted%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Mario%20no%20Photopi%20SmartMedia/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Misc/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Misc%20%28Manual%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Misc%20%28Wallpaper%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20New%20Nintendo%203DS%20%28Decrypted%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20New%20Nintendo%203DS%20%28Digital%29%20%28Deprecated%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20New%20Nintendo%203DS%20%28Encrypted%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%203DS%20%28Decrypted%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%203DS%20%28Digital%29%20%28CDN%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%203DS%20%28Digital%29%20%28Deprecated%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%203DS%20%28Digital%29%20%28Dev%20ROMs%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%203DS%20%28Digital%29%20%28Pre-Install%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%203DS%20%28Encrypted%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%2064%20%28BigEndian%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%2064%20%28ByteSwapped%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%2064DD/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20DS%20%28DSvision%20SD%20cards%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20DS%20%28Decrypted%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20DS%20%28Download%20Play%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20DS%20%28Encrypted%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20DSi%20%28Decrypted%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20DSi%20%28Digital%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20DSi%20%28Digital%29%20%28CDN%29%20%28Decrypted%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20DSi%20%28Digital%29%20%28CDN%29%20%28Encrypted%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20DSi%20%28Encrypted%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20%28Headered%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20%28Headerless%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20GameCube%20%28NPDP%20Carts%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Play-Yan/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Pokemon%20Mini/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Satellaview/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Sufami%20Turbo/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Virtual%20Boy/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Wii%20%28Digital%29%20%28CDN%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Wii%20U%20%28Digital%29%20%28CDN%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Wii%20U%20%28Digital%29%20%28CDN%29%20%28Dev%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Wii%20U%20%28Digital%29%20%28CDN%29%20%28Lotcheck%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nintendo%20-%20amiibo/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Nokia%20-%20N-Gage%20%28WIP%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Non-Redump%20-%20Apple-Bandai%20-%20Pippin/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Non-Redump%20-%20Atari%20-%20Atari%20Jaguar%20CD/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Non-Redump%20-%20Audio%20CD/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Non-Redump%20-%20NEC%20-%20PC%20Engine%20CD%20%2B%20TurboGrafx%20CD/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Non-Redump%20-%20Nintendo%20-%20Nintendo%20GameCube/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Non-Redump%20-%20Panasonic%20-%203DO%20Interactive%20Multiplayer/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Non-Redump%20-%20Philips%20-%20CD-i/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Non-Redump%20-%20Sega%20-%20Dreamcast/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Non-Redump%20-%20Sega%20-%20Sega%20Mega%20CD%20%2B%20Sega%20CD/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Non-Redump%20-%20Sega%20-%20Sega%20Saturn/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Non-Redump%20-%20Sony%20-%20PlayStation/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Non-Redump%20-%20Sony%20-%20PlayStation%202/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Non-Redump%20-%20Sony%20-%20PlayStation%20Portable/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Ouya%20-%20Ouya/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Philips%20-%20Videopac%2B/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/RCA%20-%20Studio%20II/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/SNK%20-%20Neo%20Geo%20Pocket/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/SNK%20-%20Neo%20Geo%20Pocket%20Color/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sanyo%20-%20MBC-550%20%28Flux%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sega%20-%2032X/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sega%20-%20Beena/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sega%20-%20Game%20Gear/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sega%20-%20Master%20System%20-%20Mark%20III/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sega%20-%20Mega%20Drive%20-%20Genesis/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sega%20-%20PICO/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sega%20-%20SG-1000/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Seta%20-%20Aleck64%20%28BigEndian%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Seta%20-%20Aleck64%20%28ByteSwapped%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sharp%20-%20MZ-2200%20%28Waveform%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sharp%20-%20MZ-700%20%28Waveform%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sharp%20-%20X1%20%28Waveform%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sharp%20-%20X68000%20%28Flux%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sinclair%20-%20ZX%20Spectrum%20%2B3/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sony%20-%20PlayStation%20%28PS%20one%20Classics%29%20%28PSN%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sony%20-%20PlayStation%203%20%28PSN%29%20%28Content%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sony%20-%20PlayStation%203%20%28PSN%29%20%28Updates%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sony%20-%20PlayStation%20Mobile%20%28PSN%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sony%20-%20PlayStation%20Portable%20%28PSN%29%20%28Encrypted%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sony%20-%20PlayStation%20Vita%20%28PSN%29%20%28Content%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Sony%20-%20PlayStation%20Vita%20%28PSN%29%20%28Updates%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Source%20Code%20-%20Apple%20-%20II/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Source%20Code%20-%20Apple%20-%20IIGS/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Source%20Code%20-%20Atari%20-%202600/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Source%20Code%20-%20Atari%20-%208-bit%20Family/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Source%20Code%20-%20IBM%20-%20PC%20and%20Compatibles/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Source%20Code%20-%20Mobile%20-%20Palm%20OS/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Source%20Code%20-%20Nintendo%20-%20Game%20Boy%20Advance/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Source%20Code%20-%20Nintendo%20-%20Nintendo%20-%20Game%20Boy%20Color/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Source%20Code%20-%20Nintendo%20-%20Nintendo%20DS/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Source%20Code%20-%20Nintendo%20-%20Nintendo%20Entertainment%20System/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Source%20Code%20-%20Nintendo%20-%20Nintendo%20GameCube/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Source%20Code%20-%20Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Source%20Code%20-%20VM%20Labs%20-%20NUON/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Source%20Code%20-%20Various/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/TeleNova%20-%20Compis%20%28Flux%29/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Texas%20Instruments%20-%20TI-99-4A%20%28A2R%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Tiger%20-%20Game.com/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Toshiba%20-%20Pasopia%20%28BIN%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Toshiba%20-%20Pasopia%20%28WAV%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Toshiba%20-%20Visicom/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Microsoft%20-%20Xbox%20360%20%28Title%20Updates%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Nintendo%20-%20Nintendo%203DS%20%28Digital%29%20%28Updates%20and%20DLC%29%20%28Decrypted%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Nintendo%20-%20Nintendo%203DS%20%28Digital%29%20%28Updates%20and%20DLC%29%20%28Encrypted%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Nintendo%20-%20Wii%20%28Digital%29%20%28Deprecated%29%20%28WAD%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Nintendo%20-%20Wii%20%28Digital%29%20%28Split%20DLC%29%20%28Deprecated%29%20%28WAD%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Nintendo%20-%20Wii%20U%20%28Digital%29%20%28Deprecated%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Sony%20-%20PlayStation%203%20%28PSN%29%20%28Decrypted%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Sony%20-%20PlayStation%20Portable%20%28PSN%29%20%28Decrypted%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Sony%20-%20PlayStation%20Portable%20%28PSX2PSP%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Sony%20-%20PlayStation%20Portable%20%28UMD%20Music%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Sony%20-%20PlayStation%20Portable%20%28UMD%20Video%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Sony%20-%20PlayStation%20Vita%20%28BlackFinPSV%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Sony%20-%20PlayStation%20Vita%20%28NoNpDrm%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Sony%20-%20PlayStation%20Vita%20%28PSN%29%20%28Decrypted%29%20%28VPK%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Sony%20-%20PlayStation%20Vita%20%28PSVgameSD%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Unofficial%20-%20Sony%20-%20PlayStation%20Vita%20%28VPK%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/VM%20Labs%20-%20NUON%20%28Digital%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/VTech%20-%20CreatiVision/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/VTech%20-%20V.Smile/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Watara%20-%20Supervision/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Welback%20-%20Mega%20Duck/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Yamaha%20-%20Copera/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/Zeebo%20-%20Zeebo/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/iQue%20-%20iQue%20%28CDN%29/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/No-Intro/iQue%20-%20iQue%20%28Decrypted%29/

# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Acorn%20-%20Archimedes/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Apple%20-%20Macintosh/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Apple%20-%20Macintosh%20-%20SBI%20Subchannels/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Hasbro%20-%20VideoNow/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Hasbro%20-%20VideoNow%20Color/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Hasbro%20-%20VideoNow%20Jr/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Hasbro%20-%20VideoNow%20XP/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Konami%20-%20FireBeat/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Konami%20-%20M2/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Konami%20-%20System%20573/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Konami%20-%20System%20GV/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Konami%20-%20e-Amusement/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Namco%20-%20Sega%20-%20Nintendo%20-%20Triforce/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Namco%20-%20Sega%20-%20Nintendo%20-%20Triforce%20-%20GDI%20Files/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Namco%20-%20System%20246/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Sega%20-%20Chihiro/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Sega%20-%20Chihiro%20-%20GDI%20Files/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Sega%20-%20Lindbergh/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Sega%20-%20Naomi/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Sega%20-%20Naomi%20-%20GDI%20Files/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Sega%20-%20Naomi%202/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Sega%20-%20Naomi%202%20-%20GDI%20Files/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Sega%20-%20RingEdge/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Arcade%20-%20Sega%20-%20RingEdge%202/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Atari%20-%20Jaguar%20CD%20Interactive%20Multimedia%20System/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Audio%20CD/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/BD-Video/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Bandai%20-%20Pippin/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Bandai%20-%20Playdia%20Quick%20Interactive%20System/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Commodore%20-%20Amiga%20CD/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Commodore%20-%20Amiga%20CD32/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Commodore%20-%20Amiga%20CDTV/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Fujitsu%20-%20FM-Towns/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/HD%20DVD-Video/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/IBM%20-%20PC%20compatible/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/IBM%20-%20PC%20compatible%20-%20SBI%20Subchannels/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Incredible%20Technologies%20-%20Eagle/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Mattel%20-%20Fisher-Price%20iXL/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Mattel%20-%20HyperScan/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Memorex%20-%20Visual%20Information%20System/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Microsoft%20-%20Xbox/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Microsoft%20-%20Xbox%20-%20BIOS%20Images/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Microsoft%20-%20Xbox%20360/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/NEC%20-%20PC%20Engine%20CD%20%26%20TurboGrafx%20CD/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/NEC%20-%20PC-88%20series/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/NEC%20-%20PC-98%20series/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/NEC%20-%20PC-FX%20%26%20PC-FXGA/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Navisoft%20-%20Naviken%202.1/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20BIOS%20Images/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Nintendo%20-%20Wii%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Nintendo%20-%20Wii%20U%20-%20Disc%20Keys/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Nintendo%20-%20Wii%20U%20-%20WUX/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Palm/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Panasonic%20-%203DO%20Interactive%20Multiplayer/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Panasonic%20-%20M2/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Philips%20-%20CD-i/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Photo%20CD/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/PlayStation%20GameShark%20Updates/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Pocket%20PC/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/SNK%20-%20Neo%20Geo%20CD/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sega%20-%20Dreamcast/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sega%20-%20Dreamcast%20-%20GDI%20Files/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sega%20-%20Mega%20CD%20%26%20Sega%20CD/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sega%20-%20Prologue%2021/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sega%20-%20Saturn/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sharp%20-%20X68000/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation%20-%20BIOS%20Images/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation%20-%20SBI%20Subchannels/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation%202/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation%202%20-%20BIOS%20Images/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation%203/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation%203%20-%20Disc%20Keys/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation%203%20-%20Disc%20Keys%20TXT/
wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation%20Portable/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/TAB-Austria%20-%20Quizard/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Tao%20-%20iKTV/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Tomy%20-%20Kiss-Site/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/VM%20Labs%20-%20NUON/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/VTech%20-%20V.Flash%20%26%20V.Smile%20Pro/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/Video%20CD/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/ZAPiT%20Games%20-%20Game%20Wave%20Family%20Entertainment%20System/
# wget -m -np -c -e robots=off -R "index.html*" https://myrient.erista.me/files/Redump/funworld%20-%20Photo%20Play/
