#!/bin/sh
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/ACT - Apricot PC Xi' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/APF - Imagination Machine' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/APF - MP-1000' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Acorn - Archimedes  (ADF)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Acorn - Archimedes  (JFD)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Acorn - Atom  (Tapes)  (UEF)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Acorn - Risc PC  (Pauline)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Acorn RISC OS - Flash Media  (Misc)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Amstrad - CPC  (FluxDumps)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Amstrad - CPC  (Misc)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Analogue - Analogue Pocket' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - I  (Tapes)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - II  (A2R)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - II  (WOZ)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - II  (Waveform)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - II Plus  (Flux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - II Plus  (WOZ)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - IIGS  (A2R)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - IIGS  (WOZ)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - IIe  (A2R)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - IIe  (Kryoflux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - IIe  (WOZ)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - Macintosh  (A2R)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - Macintosh  (BETA)  (Bitstreams)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - Macintosh  (BETA)  (FluxDumps)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - Macintosh  (DC42)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - Macintosh  (KryoFlux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - Macintosh  (Uncategorized)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple - Macintosh  (WOZ)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Apple-Bandai - Pippin  (Floppies)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Atari - 2600' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Atari - 5200' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Atari - 7800' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Atari - 8-bit Family' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Atari - 8-bit Family  (Kryoflux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Atari - Jaguar  (J64)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Atari - Jaguar  (ROM)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Atari - Lynx' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Atari - ST' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Atari - ST  (Flux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Bally - Astrocade' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Bally - Astrocade  (Tapes)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Bally - Astrocade  (Tapes)  (WAV)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Bandai - Design Master Denshi Mangajuku' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Bandai - Gundam RX-78' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Bandai - WonderSwan' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Bandai - WonderSwan Color' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Benesse - Pocket Challenge V2' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Benesse - Pocket Challenge W' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Bit Corporation - Gamate' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Casio - Loopy' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Casio - PV-1000' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Coleco - ColecoVision' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Commodore - Amiga' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Commodore - Amiga  (Flux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Commodore - Commodore 64' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Commodore - Commodore 64  (PP)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Commodore - Commodore 64  (Tapes)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Commodore - Plus-4' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Commodore - VIC-20' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Emerson - Arcadia 2001' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Entex - Adventure Vision' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Epoch - Game Pocket Computer' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Epoch - Super Cassette Vision' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Fairchild - Channel F' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Fujitsu - FM Towns  (KryoFlux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Fujitsu - FM-7  (Flux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Fujitsu - FM-7  (Waveform)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Fujitsu - FMR50  (Flux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Fukutake Publishing - StudyBox' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Funtech - Super Acan' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/GCE - Vectrex' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/GamePark - GP2X' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/GamePark - GP32' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Google - Android  (Amazon Appstore)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Google - Android  (Misc)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Google - Android  (Samsung Galaxy Apps)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Hartung - Game Master' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Hitachi - S1  (Waveform)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/IBM - PC and Compatibles  (Digital)  (Getchu.com)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/IBM - PC and Compatibles  (Digital)  (Misc)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/IBM - PC and Compatibles  (Digital)  (Steam)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/IBM - PC and Compatibles  (Digital)  (itch.io)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Interton - VC 4000' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Konami - Picno' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/LeapFrog - LeapPad' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/LeapFrog - Leapster Learning Game System' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Luxor - ABC 800  (Flux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Magnavox - Odyssey 2' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Mattel - Intellivision' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Microsoft - MSX' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Microsoft - MSX2' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Microsoft - Xbox  (Development Kit Hard Drives)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Microsoft - Xbox 360  (Digital)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Milton-Bradley - Omni  (Waveform)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Mobile - J2ME' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Mobile - Palm OS' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Mobile - Palm OS  (Digital)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Mobile - Pocket PC' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Mobile - Pocket PC  (Digital)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Mobile - Symbian' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/NEC - PC Engine - TurboGrafx 16' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/NEC - PC Engine SuperGrafx' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/NEC - PC-88  (Flux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/NEC - PC-88  (KryoFlux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/NEC - PC-98' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/NEC - PC-98  (Flux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/NEC - PC-98  (Greaseweazle)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/NEC - PC-98  (HardDisk)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/NEC - PC-98  (Uncategorized)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nichibutsu - My Vision' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Family BASIC  (Tapes)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Family Computer Disk System  (FDS)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Family Computer Disk System  (FDSStickRAW)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Family Computer Disk System  (QD)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Family Computer Network System' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Game & Watch' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Game Boy' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Game Boy Advance' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Game Boy Advance  (Multiboot)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Game Boy Advance  (Video)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Game Boy Advance  (e-Reader)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Game Boy Color' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Kiosk Video Compact Flash  (CardImage)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Kiosk Video Compact Flash  (Extracted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Mario no Photopi SmartMedia' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Misc' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Misc  (Manual)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Misc  (Wallpaper)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - New Nintendo 3DS  (Decrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - New Nintendo 3DS  (Digital)  (Deprecated)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - New Nintendo 3DS  (Encrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo 3DS  (Decrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo 3DS  (Digital)  (CDN)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo 3DS  (Digital)  (Deprecated)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo 3DS  (Digital)  (Dev ROMs)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo 3DS  (Digital)  (Pre-Install)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo 3DS  (Encrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo 64  (BigEndian)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo 64  (ByteSwapped)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo 64DD' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo DS  (DSvision SD cards)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo DS  (Decrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo DS  (Download Play)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo DS  (Encrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo DSi  (Decrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo DSi  (Digital)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo DSi  (Digital)  (CDN)  (Decrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo DSi  (Digital)  (CDN)  (Encrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo DSi  (Encrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo Entertainment System  (Headered)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo Entertainment System  (Headerless)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Nintendo GameCube  (NPDP Carts)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Play-Yan' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Pokemon Mini' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Satellaview' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Sufami Turbo' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Super Nintendo Entertainment System' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Virtual Boy' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Wii  (Digital)  (CDN)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Wii U  (Digital)  (CDN)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Wii U  (Digital)  (CDN)  (Dev)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - Wii U  (Digital)  (CDN)  (Lotcheck)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nintendo - amiibo' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Nokia - N-Gage  (WIP)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Non-Redump - Apple-Bandai - Pippin' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Non-Redump - Atari - Atari Jaguar CD' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Non-Redump - Audio CD' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Non-Redump - NEC - PC Engine CD + TurboGrafx CD' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Non-Redump - Nintendo - Nintendo GameCube' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Non-Redump - Panasonic - 3DO Interactive Multiplayer' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Non-Redump - Philips - CD-i' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Non-Redump - Sega - Dreamcast' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Non-Redump - Sega - Sega Mega CD + Sega CD' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Non-Redump - Sega - Sega Saturn' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Non-Redump - Sony - PlayStation' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Non-Redump - Sony - PlayStation 2' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Non-Redump - Sony - PlayStation Portable' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Ouya - Ouya' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Philips - Videopac+' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/RCA - Studio II' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/SNK - Neo Geo Pocket' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/SNK - Neo Geo Pocket Color' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sanyo - MBC-550  (Flux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sega - 32X' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sega - Beena' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sega - Game Gear' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sega - Master System - Mark III' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sega - Mega Drive - Genesis' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sega - PICO' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sega - SG-1000' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Seta - Aleck64  (BigEndian)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Seta - Aleck64  (ByteSwapped)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sharp - MZ-2200  (Waveform)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sharp - MZ-700  (Waveform)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sharp - X1  (Waveform)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sharp - X68000  (Flux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sinclair - ZX Spectrum +3' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sony - PlayStation  (PS one Classics)  (PSN)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sony - PlayStation 3  (PSN)  (Content)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sony - PlayStation 3  (PSN)  (Updates)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sony - PlayStation Mobile  (PSN)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sony - PlayStation Portable  (PSN)  (Encrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sony - PlayStation Vita  (PSN)  (Content)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Sony - PlayStation Vita  (PSN)  (Updates)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Source Code - Apple - II' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Source Code - Apple - IIGS' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Source Code - Atari - 2600' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Source Code - Atari - 8-bit Family' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Source Code - IBM - PC and Compatibles' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Source Code - Mobile - Palm OS' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Source Code - Nintendo - Game Boy Advance' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Source Code - Nintendo - Nintendo - Game Boy Color' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Source Code - Nintendo - Nintendo DS' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Source Code - Nintendo - Nintendo Entertainment System' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Source Code - Nintendo - Nintendo GameCube' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Source Code - Nintendo - Super Nintendo Entertainment System' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Source Code - VM Labs - NUON' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Source Code - Various' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/TeleNova - Compis  (Flux)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Texas Instruments - TI-99-4A  (A2R)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Tiger - Game.com' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Toshiba - Pasopia  (BIN)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Toshiba - Pasopia  (WAV)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Toshiba - Visicom' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Microsoft - Xbox 360  (Title Updates)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Nintendo - Nintendo 3DS  (Digital)  (Updates and DLC)  (Decrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Nintendo - Nintendo 3DS  (Digital)  (Updates and DLC)  (Encrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Nintendo - Wii  (Digital)  (Deprecated)  (WAD)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Nintendo - Wii  (Digital)  (Split DLC)  (Deprecated)  (WAD)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Nintendo - Wii U  (Digital)  (Deprecated)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Sony - PlayStation 3  (PSN)  (Decrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Sony - PlayStation Portable  (PSN)  (Decrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Sony - PlayStation Portable  (PSX2PSP)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Sony - PlayStation Portable  (UMD Music)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Sony - PlayStation Portable  (UMD Video)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Sony - PlayStation Vita  (BlackFinPSV)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Sony - PlayStation Vita  (NoNpDrm)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Sony - PlayStation Vita  (PSN)  (Decrypted)  (VPK)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Sony - PlayStation Vita  (PSVgameSD)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Unofficial - Sony - PlayStation Vita  (VPK)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/VM Labs - NUON  (Digital)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/VTech - CreatiVision' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/VTech - V.Smile' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Watara - Supervision' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Welback - Mega Duck' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Yamaha - Copera' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/Zeebo - Zeebo' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/iQue - iQue  (CDN)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/No-Intro/iQue - iQue  (Decrypted)' '/mnt/user/ROMs/myrient.erista.me/files/No-Intro'

# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Acorn - Archimedes' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Apple - Macintosh' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Apple - Macintosh - SBI Subchannels' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Hasbro - VideoNow' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Hasbro - VideoNow Color' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Hasbro - VideoNow Jr' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Hasbro - VideoNow XP' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Konami - FireBeat' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Konami - M2' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Konami - System 573' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Konami - System GV' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Konami - e-Amusement' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Namco - Sega - Nintendo - Triforce' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Namco - Sega - Nintendo - Triforce - GDI Files' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Namco - System 246' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Sega - Chihiro' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Sega - Chihiro - GDI Files' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Sega - Lindbergh' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Sega - Naomi' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Sega - Naomi - GDI Files' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Sega - Naomi 2' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Sega - Naomi 2 - GDI Files' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Sega - RingEdge' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Arcade - Sega - RingEdge 2' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Atari - Jaguar CD Interactive Multimedia System' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Audio CD' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/BD-Video' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Bandai - Pippin' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Bandai - Playdia Quick Interactive System' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Commodore - Amiga CD' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Commodore - Amiga CD32' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Commodore - Amiga CDTV' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Fujitsu - FM-Towns' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/HD DVD-Video' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/IBM - PC compatible' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/IBM - PC compatible - SBI Subchannels' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Incredible Technologies - Eagle' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Mattel - Fisher-Price iXL' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Mattel - HyperScan' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Memorex - Visual Information System' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Microsoft - Xbox' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Microsoft - Xbox - BIOS Images' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Microsoft - Xbox 360' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/NEC - PC Engine CD & TurboGrafx CD' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/NEC - PC-88 series' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/NEC - PC-98 series' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/NEC - PC-FX & PC-FXGA' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Navisoft - Naviken 2.1' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Nintendo - GameCube - BIOS Images' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Nintendo - GameCube - NKit RVZ [zstd-19-128k]' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Nintendo - Wii - NKit RVZ [zstd-19-128k]' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Nintendo - Wii U - Disc Keys' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Nintendo - Wii U - WUX' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Palm' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Panasonic - 3DO Interactive Multiplayer' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Panasonic - M2' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Philips - CD-i' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Photo CD' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/PlayStation GameShark Updates' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Pocket PC' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/SNK - Neo Geo CD' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sega - Dreamcast' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sega - Dreamcast - GDI Files' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sega - Mega CD & Sega CD' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sega - Prologue 21' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sega - Saturn' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sharp - X68000' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sony - PlayStation' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sony - PlayStation - BIOS Images' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sony - PlayStation - SBI Subchannels' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sony - PlayStation 2' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sony - PlayStation 2 - BIOS Images' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sony - PlayStation 3' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sony - PlayStation 3 - Disc Keys' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sony - PlayStation 3 - Disc Keys TXT' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Sony - PlayStation Portable' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/TAB-Austria - Quizard' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Tao - iKTV' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Tomy - Kiss-Site' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/VM Labs - NUON' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/VTech - V.Flash & V.Smile Pro' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/Video CD' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/ZAPiT Games - Game Wave Family Entertainment System' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
# rsync -avP 'rsync://rsync.myrient.erista.me/files/Redump/funworld - Photo Play' '/mnt/user/ROMs/myrient.erista.me/files/Redump'
